# Generated by Django 3.0.7 on 2020-06-11 09:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20200611_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggallery',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gallery_images', to='blogapp.BlogPage'),
        ),
    ]
